### ISSUE TITLE
Error inserting images with Django 1.11, no problems with 1.10

### ISSUE THREAD

**Issue by tylerecouture** [summernote/django-summernote#187]
I tried upgrading to Django 1.11.2, but Summernote gives me this error when I try to insert an image:

```
Got an error uploading an image: AttributeError at /summernote/upload_attachment/
This QueryDict instance is immutable
```

Here's the traceback:

```
Internal Server Error: /summernote/upload_attachment/
Traceback (most recent call last):
  File "/home/couture/Developer/hackerspace/lib/python3.4/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/couture/Developer/hackerspace/lib/python3.4/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/couture/Developer/hackerspace/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/couture/Developer/hackerspace/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/couture/Developer/hackerspace/lib/python3.4/site-packages/django_summernote/views.py", line 59, in upload_attachment
    request.POST.pop("csrfmiddlewaretoken", None)
  File "/home/couture/Developer/hackerspace/lib/python3.4/site-packages/django/http/request.py", line 473, in pop
    self._assert_mutable()
  File "/home/couture/Developer/hackerspace/lib/python3.4/site-packages/django/http/request.py", line 431, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
[04/Jun/2017 21:38:18] "POST /summernote/upload_attachment/ HTTP/1.1" 500 19091
```

**Comment by lqez** [comment]
This was fixed by https://github.com/summernote/django-summernote/commit/d887f1c5ad1f611e300f1868485efba9c2b34488. Please use the latest version. 
Ref: https://github.com/summernote/django-summernote/issues/183
