### ISSUE TITLE
I got error related with jquery

### ISSUE THREAD

**Issue by YuTaeseong** [summernote/django-summernote#209]
(index):41 Uncaught TypeError: $summernote.summernote is not a function
    at HTMLDocument.<anonymous> ((index):41)
    at fire (jquery-2.2.4.js:3187)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.js:3317)
    at Function.ready (jquery-2.2.4.js:3536)
    at HTMLDocument.completed (jquery-2.2.4.js:3552)

how can I solve it?

**Comment by YuTaeseong** [comment]
I can summernote when I add 
"<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script> 
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script> 


<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.js"></script>"

But I got new error

jquery.js:3860 jQuery.Deferred exception: ResizeSensor is not defined ReferenceError: ResizeSensor is not defined
    at HTMLDivElement.onInit (http://localhost:8000/:55:17)
    at Context.triggerEvent (http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.js:1691:18)
    at HTMLDivElement.<anonymous> (http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.js:1820:36)
    at Function.each (http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js:362:19)
    at jQuery.fn.init.each (http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js:157:17)
    at jQuery.fn.init.summernote (http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.js:1815:12)
    at HTMLDocument.<anonymous> (http://localhost:8000/:47:17)
    at mightThrow (http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js:3583:29)
    at process (http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js:3651:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3860
process @ jquery.js:3655
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
jquery.js:3869 Uncaught ReferenceError: ResizeSensor is not defined
    at HTMLDivElement.onInit ((index):55)
    at Context.triggerEvent (summernote.js:1691)
    at HTMLDivElement.<anonymous> (summernote.js:1820)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.summernote (summernote.js:1815)
    at HTMLDocument.<anonymous> ((index):47)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)

**Comment by lqez** [comment]
It looks like this error was caused by missing `ResizeSensor.js` It was added by https://github.com/summernote/django-summernote/commit/56873e689a98d7836a46ca03acf7b6274dbb60e5 to enhance calculation of editor height and dropdown position. Please try to re-collect static files.
