### ISSUE TITLE
Setting attachment_upload_to results in a missing migration

### ISSUE THREAD

**Issue by jmsmkn** [summernote/django-summernote#335]
If I add `attachment_upload_to` to `SUMMERNOTE_CONFIG` this results in a missing migration, such that running `manage.py makemigrations` results in an error:

```
Migrations for 'django_summernote':
  /usr/local/lib/python3.6/site-packages/django_summernote/migrations/0003_auto_20181101_0931.py
    - Alter field file on attachment
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 184, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 223, in write_migration_files
    with open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/django_summernote/migrations/0003_auto_20181101_0931.py'
```

It would be great if there's a nicer way to handle this, other than implementing my own `attachment_model`.

**Comment by lqez** [comment]
I never thought this could be a problem. Thank you for reporting.
