### ISSUE TITLE
Summernote migration 0003_alter_attachment_id.py missing in pip package.

### ISSUE THREAD

**Issue by alexdeathway** [summernote/django-summernote#492]
This causes permission issue with environment which don't allow or give root access and app try to create migration in that case.

**Comment by alexdeathway** [comment]
environment: docker container
name:django_1
python:3.8
django_summernote: 0.8.20.0
issue: PermissionError
additional_issue_info:PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/django_summernote/migrations/0003_alter_attachment_id.py'

error :
```
django_1    | Migrations for 'django_summernote':
django_1    |   /usr/local/lib/python3.8/site-packages/django_summernote/migrations/0003_alter_attachment_id.py
django_1    |     - Alter field id on attachment
django_1    | Traceback (most recent call last):
django_1    |   File "manage.py", line 22, in <module>
django_1    |     main()
django_1    |   File "manage.py", line 18, in main
django_1    |     execute_from_command_line(sys.argv)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
django_1    |     utility.execute()
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
django_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
django_1    |     self.execute(*args, **cmd_options)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
django_1    |     output = self.handle(*args, **options)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
django_1    |     res = handle_func(*args, **kwargs)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 190, in handle
django_1    |     self.write_migration_files(changes)
django_1    |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 228, in write_migration_files
django_1    |     with open(writer.path, "w", encoding='utf-8') as fh:
django_1    | PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/django_summernote/migrations/0003_alter_attachment_id.py'
```
